import = [
  "~/.config/alacritty/theme.toml"
]

[env]
TERM = "xterm-256color"

[window]
decorations_theme_variant = "Dark"
opacity = 0.9
blur = true
dynamic_padding = true

[font]
normal = {family = "FiraCode Nerd Font"}
size = 13
